# Generated by Django 4.1.5 on 2023-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Cover', models.CharField(choices=[('H', 'HARD'), ('S', 'SOFT')], max_length=4)),
                ('Inventory', models.PositiveIntegerField()),
                ('Daily_fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
